### ISSUE TITLE
Pinned notes

### ISSUE THREAD

**Issue by colebemis** [lumen-notes/lumen#115]

**Comment by colebemis** [comment]
What if you could pin notes or tags to the command menu?

**Comment by hisamafahri** [comment]
FYI I have already explored this a while ago.

My initial thought on this was as simple as that the pinned notes have a `#pinned` tag. And the notes are automatically sorted with the `#pinned` tags first (to make it appear on top).

But, been busy lately so probably working on this in the near future.
