### ISSUE TITLE
Homologate shortcuts

### ISSUE THREAD

**Issue by fxsalazar** [lumen-notes/lumen#180]
I'm having issues with some shortcuts while editing notes and navigating the panels:
- **⌘ + ⇧ + ←** should select all the text form cursor to start of the line, instead it takes you to the left panel. Maybe navigate panels with **⌘+⌥ + [arrow]**
- **⌘ + X** I see that when text is selected, it cuts, else closes the panel. I'm so used to cut lines with it, that it becomes frustrating when it closes the note. Maybe change closing to **⌘ + Esc** or even just **Esc**; knowing that **⌘ + W** closes the tab, so it's 🙅🏽 
- **⌘ + .** unresponsive 🤷🏽  when installed as a PWA.
- Markdown shortcuts standards define **⌘ + i** for _italics_ and in Lumen is for creating a New Note 😰 Add support for those standards could be good. i.e.  **⌘ + b** for **bold**. I'm not sure what to propose for a new note shortcut. 💭 
- **⌘ + F** it depends on the focus because is the search for the browser. Maybe just using  **/** as Github and other web sites do. 

I see that you are considering #176 (I could suggest adding also support for vscode-mode too) but it could be better to homologate the basics like the one I'm exposing.

**Comment by colebemis** [comment]
This is amazing feedback. Thank you, @fxsalazar! All your suggestions sound reasonable to me. Want to open a PR?

**Comment by colebemis** [comment]
Another shortcut that we should probably change:

<kbd>⌘</kbd><kbd>⇧</kbd><kbd>C</kbd> to copy the ID of the note is overridden by "copy URL" in the Arc browser.

**Comment by fxsalazar** [comment]
I sure will do a PR with the first tests; Let's do a list of those one that need update with their substitution.

**Comment by colebemis** [comment]
I'm going to track this work in #220
