### ISSUE TITLE
Card/List dropdown should be a toggle

### ISSUE THREAD

**Issue by NetOpWibby** [lumen-notes/lumen#187]
<img width="172" alt="SS 2023-10-13 at 10 39 25 PM" src="https://github.com/lumen-notes/lumen/assets/1288356/c375299e-55e4-46a9-b067-06cdb82f5e91">

Unless of course, there will be more options. In that case, I would like to instead cycle through all options instead of a dropdown (maybe a config thing).

**Comment by colebemis** [comment]
This is great feedback. Want to open a PR to turn it into a toggle button?

**Comment by NetOpWibby** [comment]
React isn't my cup of tea (Svelte is my go-to), but I'll do my best.

**Comment by NetOpWibby** [comment]
How is local development supposed to work? `npm run dev` brings up the Github authentication button but clicking it leads to Github's 404.

**Comment by colebemis** [comment]
@NetOpWibby Try `npm run dev:netlify` instead.

**Comment by colebemis** [comment]
There are more detailed instructions here: https://github.com/lumen-notes/lumen/blob/main/CONTRIBUTING.md

**Comment by NetOpWibby** [comment]
No idea how I missed that file
