### ISSUE TITLE
Fix push error

### ISSUE THREAD

**Issue by colebemis** [lumen-notes/lumen#201]
![Image](https://github.com/lumen-notes/lumen/assets/4608155/e1747a1b-3ce1-4a34-bb6f-8e1afc0d3c1b)

**Comment by RobertBolender** [comment]
If at all possible, the app should not throw away what the user has typed. I lost the contents of a note when I hit this bug.

**Comment by colebemis** [comment]
> If at all possible, the app should not throw away what the user has typed.

💯 agreed.

> EDIT: the note that I thought I had lost reappeared when I reauthenticated today, although it had been invisible previously and had not been found with a search.

Oh strange. I've run into some weird behavior when dealing with merges. I want to make a better UI to surface and resolve these errors.

**Comment by colebemis** [comment]
I haven't seen this error in a while. Closing for now
