### ISSUE TITLE
Expand command menu functionality

### ISSUE THREAD

**Issue by colebemis** [lumen-notes/lumen#204]
## Inspiration

- https://app.campsite.design

**Comment by zaaakher** [comment]
You mean something like this? 👇

![image](https://github.com/lumen-notes/lumen/assets/46135573/4501b24b-a98c-4d1d-a3fc-689051334ba8)

**Comment by colebemis** [comment]
@zaaakher yup!

**Comment by colebemis** [comment]
I'm going to break this into more specific sub-issues
