### ISSUE TITLE
Error: emails.find is not a function

### ISSUE THREAD

**Issue by zaaakher** [lumen-notes/lumen#211]
I get the following error when I try to login via github:
![image](https://github.com/lumen-notes/lumen/assets/46135573/b6954280-6f70-487c-954f-76744bb619ba)

I fixed it by deleting my cookies and visiting app.uselumen.com again and authorized github again.

**Comment by colebemis** [comment]
I _think_ this is fixed. Feel free to re-open if you run into this error again.
