### ISSUE TITLE
Syncing takes a long time

### ISSUE THREAD

**Issue by NetOpWibby** [lumen-notes/lumen#236]
I like writing notes in the calendar view at night on my phone and when I wake up, my notes aren't in the desktop version. I have to manually trigger syncing and stare at it to make sure my latest changes aren't overwritten.

**Comment by colebemis** [comment]
That's strange. I just shipped some updates to the syncing system that might fix this for you. 

Can you try quitting the app and refreshing a couple times (to clear the service worker cache and make sure you have the latest version) and let me know if you're still having this issue?

**Comment by NetOpWibby** [comment]
My iPhone version isn't updated, my macOS version just now ended with a sync error. Restarted the sync.

**Comment by colebemis** [comment]
Can you send me a screenshot of the DevTools console?

**Comment by NetOpWibby** [comment]
Idk how to view the console with Safari's wrapped app version.

**Comment by NetOpWibby** [comment]
My phone homescreen app finally updated with the latest content

**Comment by colebemis** [comment]
@NetOpWibby Are you still having this issue?

FYI, you can open the console via the Safari `Develop` menu:



![Image](https://github.com/lumen-notes/lumen/assets/4608155/94e2cb61-d065-4f04-acda-6d5dd3f3a2b7)

If you're still having this issue, could you try clearing localStorage and IndexedDB?



![Image](https://github.com/lumen-notes/lumen/assets/4608155/bee73742-2bc9-4f1d-bcc6-1c63358c15e3)



![Image](https://github.com/lumen-notes/lumen/assets/4608155/baabf640-7f08-421f-a0a4-675f12d54bb1)

**Comment by NetOpWibby** [comment]
Ah! Good to know!

I'm not having this issue at the moment but I cleared everything and logged in again anyway. I'll close this issue for now.
