### ISSUE TITLE
Copy icon in codeblocks

### ISSUE THREAD

**Issue by zaaakher** [lumen-notes/lumen#238]
It'd be really nice if codeblocks have a copy icon next to them so that anyone can easily copy the code in the block. Similar to how it's in README.md in github

**Comment by colebemis** [comment]
Great idea! Added to the project board. Feel free to take this on if you're interested!

**Comment by zaaakher** [comment]
I couldn't find a code block component in the `components` folder. all I could find is [this](https://github.com/lumen-notes/lumen/blob/941cf3a62a713fc2ed244ea54e3a7cf28f531052/tailwind.config.cjs#L42)  tailwind config color extension and [this](https://github.com/lumen-notes/lumen/blob/941cf3a62a713fc2ed244ea54e3a7cf28f531052/src/styles/markdown.css#L48) css styling. 

It seems it's using the built-in markdown code block. Do we need to create a new code block for this? or is there a better approach to attaching a button to the existing default code blocks?

**Comment by colebemis** [comment]
@zaaakher Here's the code block component that lives in the `src/components/markdown.tsx` file: https://github.com/lumen-notes/lumen/blob/941cf3a62a713fc2ed244ea54e3a7cf28f531052/src/components/markdown.tsx#L590C1-L594C4
