### ISSUE TITLE
19 vulnerabilities (16 moderate, 2 high, 1 critical) **in Windows**

### ISSUE THREAD

**Issue by zaaakher** [lumen-notes/lumen#245]
## Current

When I run `npm install` on my windows 10 machine I get this warning.

![image](https://github.com/lumen-notes/lumen/assets/46135573/8a7e2cbe-93b9-4c0b-9095-147b7cbd56ad)

## After
When I run `npm audit fix` it makes changes to `package-lock.json` and it takes the vulnerabilities down to 13 👇

![image](https://github.com/lumen-notes/lumen/assets/46135573/1fc8c521-6feb-41dc-a250-a60b36183114)

### @colebemis Should I make a PR for the updated `package-lock.json` ?

**Comment by colebemis** [comment]
> Should I make a PR for the updated package-lock.json?


@zaaakher yes please!

**Comment by zaaakher** [comment]
Done 👍
