### ISSUE TITLE
Close shortcut (⌘X) doesn't work while using as a Safari web app

### ISSUE THREAD

**Issue by drifkin** [lumen-notes/lumen#250]
It seems like default, grayed-out `Edit > Cut ⌘X` menu item takes precedence.

(Incidentally, never know what to call these "add to dock" apps, Safari PWAs? Apple says "Safari web apps" [here](https://support.apple.com/en-us/104996), so I went with that)

**Comment by colebemis** [comment]
I'll fix this in #220
