### ISSUE TITLE
Weird rendering/formatting from "$"

### ISSUE THREAD

**Issue by NetOpWibby** [lumen-notes/lumen#309]
<img width="139" alt="SS 2024-04-09 at 12 57 32 PM" src="https://github.com/lumen-notes/lumen/assets/1288356/81280d49-9f84-4c78-b24c-8ccaf047b1ef">

This weirdness is caused from this text:

```plain
$31960, which leaves $8k for my bills
```

If I escape the `$` with `\`, the rendering issue is fixed.

**Comment by noahgsolomon** [comment]
It should only activate when there are two dollar signs and then another two like "$$hello how are you$$" would become math. This should hopefully be an easy fix. 

```js
import remarkMath, { Options } from "remark-math"

const remarkMathOptions: Options = {
    singleDollarTextMath: false,
}

// ...
            remarkPlugins={[
                [remarkMath, remarkMathOptions],
            ]}
```

I saw this in a forum, try this and lmk if this doesn't work.
