### ISSUE TITLE
Feedback for author/s of Lumen app

### ISSUE THREAD

**Issue by leonardreidy** [lumen-notes/lumen#338]
Many thanks guys for an excellent application. I've been looking around for a solid platform for building a Zettelkasten and this meets almost all of my criteria. It is the best candidate I've seen including free, open source and proprietary solutions. The UI/UX is clean, easy and fluent; nice typography, uncluttered layouts. It has many thoughtful features such as the fullwidth layouts allowing comparison of notes and real clean approach to tags which are key to an effective Zettelkasten. The storage solution is robust and about as future-proof as it gets. I was so excited to see how bare the repository for my Lumen instance was. It might survive an apocalypse! Overall a smooth, distraction-free experience that just works and as a software engineer the codebase is a joy to sniff around.

Again, many thanks for really awesome work. Cheers!!!

**Comment by colebemis** [comment]
Thank you, @leonardreidy 🥰 

Don't hesitate to open more GitHub issues if you have any questions, feature requests, or bug reports.
