### ISSUE TITLE
missing workflow file

### ISSUE THREAD

**Issue by jaked** [lumen-notes/lumen#344]
I tried to access a repo via Lumen and got

![Image](https://github.com/lumen-notes/lumen/assets/56439/c3819ba2-9a3a-49bc-bbef-abc1565b778e)

but when I clicked the link on `lumen.yml` I got a 404.

I see I have a `lumen.yml` in my personal notes repo but I don't know if it's still needed (or if the one I have is up-to-date).

**Comment by colebemis** [comment]
Try refreshing a few times. You likely have an old version of lumen cached
