### ISSUE TITLE
ability to use "new note" keyboard shortcut while in edit mode

### ISSUE THREAD

**Issue by drifkin** [lumen-notes/lumen#351]
Now that it's reasonable to primarily stay in edit mode (mostly because you can save and stay in edit mode), I find myself reaching for `cmd-I` to create a new note. But it only works in view mode. I think it'd be nice to not have to exit edit mode first, though it could make it more likely that you'd navigate away without saving

**Comment by colebemis** [comment]
Agreed. This would be nice!

> though it could make it more likely that you'd navigate away without saving

We save "drafts" in local storage so if you accidentally navigate you can just go back without losing and edits
