### ISSUE TITLE
chinese tag

### ISSUE THREAD

**Issue by yekki** [lumen-notes/lumen#354]
Doesn't support Chinese characters tag.

**Comment by zaaakher** [comment]
Same with Arabic
![image](https://github.com/user-attachments/assets/dc33dd8b-d3f4-4197-9ffe-c45f4df21d61)

**Comment by zaaakher** [comment]
@colebemis I tried to work on a fix for this to make it accept non-english languages, but is that even possible with `micromark-util-symbol/codes` ?
