### ISSUE TITLE
can't drop media assets into notes

### ISSUE THREAD

**Issue by zaaakher** [lumen-notes/lumen#377]
Everything works fine when I drag and drop a .png or .jpg, but  when I do it with a .gif it just adds a new line and nothing happens.

I tried to manually upload the gif into the `uploads` folder of my lumen notes repo and I got the following error:

```
The following files are configured to be stored in Git LFS and must be pushed using the Git command line with Git LFS installed: uploads/animated-underline-tailwind.gif
```

So I'm guessing that's related to the issue of not being able to upload a gif to a note in lumen?

**Comment by zaaakher** [comment]
Ok I was able to upload the gif into `uploads` folder by cloning the repo into my desktop and adding the gif and then git pushing back.

Although I don't think that's technically a fix to this issue since cloning the repo and interacting with git (via terminal/github-desktop) is antithetical to the concept of lumen (in my opinion)

**Comment by zaaakher** [comment]
Ok I just experimented around to see what works and what doesn't.

Dragging and dropping any media asset (.gif, .png, jpg) doesn't work.

But when I copy the file in my pc (ctrl + c) and then go into the lumen note and paste the media (ctrl + v) it works perfectly.

So this entire issue is about dragging and dropping media into notes.

**Comment by colebemis** [comment]
Hi! Yeah, this is a known issue. I just haven't gotten around to implementing the drag-and-drop feature. It's on the roadmap: https://github.com/lumen-notes/lumen/issues/303

Closing this as a duplicate
