### ISSUE TITLE
Collapsed sectinos doesn't seem to work.

### ISSUE THREAD

**Issue by uFreezy** [lumen-notes/lumen#389]
My understanding is that Lumen uses Github Flavored markdown, however [collapsable sections](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections#creating-a-collapsed-section) don't seem to work.

This is what I'm trying to use: 
```markdown
### Knowledge Cards
<details>
<summary>Knowledge Cards</summary>
</details>
```

and this is what i see: 
<img width="676" alt="Screenshot at Aug 04 14-26-18" src="https://github.com/user-attachments/assets/d894c360-710a-4f93-89cf-69c4ef861c1b">

**Comment by colebemis** [comment]
Thanks for the issue @uFreezy! Lumen doesn't currently support HTML tags inside markdown like GitHub does. That's tracked here: https://github.com/lumen-notes/lumen/issues/9

Closing this as a duplicate
