### ISSUE TITLE
Frontmatter Blanks Screen

### ISSUE THREAD

**Issue by Docfips** [lumen-notes/lumen#421]
Good evening,

I just found this app and wanted to give it a test drive. It reminds me of Supernotes and wanted to see how it can compared.

TLDR: Anytime I would try and add the frontmatter at the top of the card, the screen goes black. I tried this in 3 browsers as well as it being in PWA mode. Every time. The only way I can get back in is to clear the cookies and caches.

```
---
---
```

https://jam.dev/c/25e5d271-1692-40f3-b2af-adf2fb5f068a

**Comment by colebemis** [comment]
Oh, very strange. Thanks for reporting this! And thanks for the Jam link!

**Comment by Docfips** [comment]
Cheers, thank you! :-)
