### ISSUE TITLE
Feature Req - Open Note

### ISSUE THREAD

**Issue by Docfips** [lumen-notes/lumen#428]
Hello,

I think I'd like to be able to open a singular note in the "main" panel, not just making it open in a side panel.

For instance, when I click on the name of a note, it opens in the secondary panel, but I can't close the parent panel so that I can work on that note specifically.

![image](https://github.com/user-attachments/assets/479d6972-f999-4ee6-a00e-98cfa29771a0)

**Comment by colebemis** [comment]
You can actually do this now by option-clicking on note links to open them in the same panel.
