### ISSUE TITLE
GitPushError: push declined due to email privacy restrictions

### ISSUE THREAD

**Issue by UshiHiraga** [lumen-notes/lumen#436]
Sync fails. In developer's console appears:

```
[start] git push
onMessage error:GH007: Your push would publish a private email address.
onMessage You can make your email public or disable this protection by visiting:
onMessage https://github.com/settings/emails
GitPushError: One or more branches were not updated: 
  - refs/heads/main: push declined due to email privacy restrictions
    at gEe (index-03b654cd.js:456:40)
    at async Object.vEe [as push] (index-03b654cd.js:456:332)
    at async cDe (index-03b654cd.js:501:34563)
    at async push (index-03b654cd.js:614:5288)
````
Even if Lumen's repo is commonly used as a private repo, disabling "Keep my email addresses private" in Github is an undesired option for some people.

**Comment by colebemis** [comment]
Thanks for reporting @UshiHiraga. Do you know what we could do in Lumen to fix this issue?

**Comment by UshiHiraga** [comment]
I guess the problem is related with the way user's email is collected in the ```getUser()``` method in ```netlify/edge-functions/github-auth.ts```

According to response schema of [/user/emails](https://docs.github.com/en/rest/users/emails#list-email-addresses-for-the-authenticated-user) endpoint, it is possible to check visibility in the email object.

```jsonc
// Example presented in github api docs.
[
  {
    "email": "octocat@github.com",
    "verified": true,
    "primary": true,
    "visibility": "public"
  }
]
```

The solution would be to collect the first primary email that is also "public". It'd be necessary to changes lines 72 and 73 to:

```javascript
  const emails = (await emailResponse.json()) as Array<{ email: string; primary: boolean; visibility: string }>
  const primaryEmail = emails.find((email) => email.primary && email.visibility === "public")
````

**Comment by UshiHiraga** [comment]
Hello. It was supposed that by checking if there was a primary and public email, one could use the app without the need of disabling `Keep my email addresses private`, but it didn't happen.

I'd like to ask if it's really necessary that email in the app be a primary email.

**Comment by colebemis** [comment]
> I'd like to ask if it's really necessary that email in the app be a primary email.

I don't think it needs to be primary. I think that that was just a good default. Maybe we choose the primary by default unless it's private, then we fallback to the first public one?

**Comment by UshiHiraga** [comment]
Maybe just choose the first public email, regardless of whether it is primary or not?

**Comment by UshiHiraga** [comment]
The PR #455 aims to solve the problem of not be able to log in without exposing my private email.
