### ISSUE TITLE
Error while creating/editing/removing a note on the website

### ISSUE THREAD

**Issue by c01nd01r** [lumen-notes/lumen#66]
Hey! 👋
When adding a note on uselumem.com, I get the error `Cannot read properties of undefined (reading 'body')`.
I opened the dev tools and found that the current index in `for...of ` does not match the list of notes.

<details>
<img width="1512" alt="Снимок экрана 2023-02-01 в 13 57 23" src="https://user-images.githubusercontent.com/3511312/216000682-94c78d25-46d3-4e1b-b093-e597dcacae9c.png">
</details>

I cloned the repository and tried to reproduce the issue locally, but on local build everything works as expected.

**Comment by colebemis** [comment]
👋 Hi, @c01nd01r! Thanks for the bug report. Do you have this workflow setup up in your repo? https://github.com/lumen-notes/lumen-template/tree/main/.github/workflows

**Comment by c01nd01r** [comment]
@colebemis Yep!
I clicked the "Use this template" button in the `lumen-notes/lumen-template` repository.
Made my repository public
https://github.com/c01nd01r/my-fast-notes

**Comment by colebemis** [comment]
@c01nd01r are you still having this issue? 

I was able to load your open source notes: ![image](https://user-images.githubusercontent.com/4608155/217113564-d36b46ed-eed2-4178-a339-2840b021a8a8.png)
