### ISSUE TITLE
Write permission is required for the workflow

### ISSUE THREAD

**Issue by ddyjis** [lumen-notes/lumen#67]
I got this error in Action

```
The workflow is not valid. .github/workflows/lumen.yml (Line: 4, Col: 3): Error calling workflow 'lumen-notes/lumen/.github/workflows/lumen.yml@main'. The workflow 'lumen-notes/lumen/.github/workflows/lumen.yml@main' is requesting 'contents: write', but is only allowed 'contents: read'.
```

(I see the same error in the template repo https://github.com/lumen-notes/lumen-template/actions/runs/3973883403/workflow)

I had to manually add write permission for the workflow in my repository in order for lumen to work properly.

Can this be fixed in the template? Or we have to update the README.md for this?

**Comment by colebemis** [comment]
Thanks for the bug report, @ddyjis! This commit should fix it: https://github.com/lumen-notes/lumen-template/commit/937eb10c8665a785b28892982aaef67662cff130
