### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by colebemis** [lumen-notes/lumen#71]
- [ ] Banner prompting user to connect their GitHub account
 - [ ] Example/getting started notes?
 - [ ] Choose existing repo (automatically create lumen workflow file if it doesn't exist)
 - [ ] Create new repo from template repo
 - [ ] Push local notes to repo after signing in and connecting a repo

**Comment by jaljiths** [comment]
Can I work on this?

**Comment by colebemis** [comment]
I appreciate the enthusiasm, @jaljiths! However, Lumen is not really in a place to accept outside contributions yet. I'll mark issues with `help wanted` when I'm ready.
